version: '2'

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:2
    restart: always
    ports:
      - 127.0.0.1:8899:80
    volumes:
      - ./drone:/data
    env_file:
      - drone/env

  drone-runner-docker:
    container_name: drone-runner-docker
    image: drone/drone-runner-docker:1
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner-docker
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
    env_file:
      - drone/env-runner
